service: hello-world-lambda
 
provider:
 name: aws
 runtime: python3.9
 region: us-east-1
 memorySize: 128
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
 pythonRequirements:
   layer: true
 wsgi:
   app: app.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   layers:
     - Ref: PythonRequirementsLambdaLayer
   events:
     - httpApi: '*'
