service: test-lambda-url
 
provider:
 name: aws
 runtime: python3.9
 region: us-east-1
 memorySize: 512
 timeout: 90
plugins:
  - serverless-wsgi
  - serverless-python-requirements
custom:
 pythonRequirements:
   layer: true
 wsgi:
   app: app.app
   packRequirements: false
functions:
 app:
   handler: wsgi_handler.handler
   layers:
     - Ref: PythonRequirementsLambdaLayer
   
   # 1 - Enable direct Lambda Function URL, this can bypass API Gateway 30s timeout
   url:
     # Allow CORS for all requests from any origin
     cors: true

   # 2 - Enable lambda through API Gateway HTTP API. Note, using API Gateway will force a 30s max timeout
   # on all endpoints
   #events:
   #  - httpApi: '*'
